###############
##
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'F35'
  SESSION: 'Img2Video'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 15
  NUM_EPOCHS: 3000
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 5
  RESUME: True
  TRAIN_PS: 32
  VAL_PS: 32
  #  TRAIN_DIR: '../Datasets/1000fps/train' # path to training data
  #  VAL_DIR: '../Datasets/1000fps/test'    # path to validation data
  TRAIN_DIR: '../Datasets/video_reduced/train' # path to training data
  VAL_DIR: '../Datasets/video_reduced/test'    # path to validation data
#  TRAIN_DIR: '../Datasets/video_min/train' # path to training data
#  VAL_DIR: '../Datasets/video_min/test'    # path to validation data
  SAVE_DIR: './ckpt'     # path to save models and images
  # SAVE_IMAGES: False
